from typing import Protocol

from .models import ProfileMetrics


class Device(Protocol):
    def ensure_ready(self) -> None: ...

    def open_profile(self, username: str) -> None: ...

    def read_profile_metrics(self) -> ProfileMetrics: ...

    def list_visible_posts(self) -> tuple[str, ...]: ...

    def open_post(self, post_id: str) -> None: ...

    def return_to_baseline(self) -> None: ...

    def restart_app(self) -> None: ...

